services:
  - type: web
    name: biskit
    env: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: BISKIT_FRONTEND_BASE_URL
        value: https://biskit.website
