#---

spring.config.activate.on-profile=default

spring.application.name=biskit

server.port=${PORT:8080}

# datasource
spring.jpa.database=h2
spring.datasource.driver-class-name=org.h2.Driver

# nombre base de datos
spring.datasource.url=jdbc:h2:file:./mydatabase
spring.datasource.username=sa
spring.datasource.password=

# consola de administracion de h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true

# datos de prueba
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

# logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true

# carga de propiedades sensibles (correo)
spring.config.import=optional:classpath:application-correo.properties

#---

spring.config.activate.on-profile=test

spring.application.name=biskit

server.port=${PORT:8080}

# datasource
spring.jpa.database=h2
spring.datasource.driver-class-name=org.h2.Driver

# nombre base de datos
spring.datasource.url=jdbc:h2:file:./testdb
spring.datasource.username=sa
spring.datasource.password=

# consola de administracion de h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true

# datos de prueba
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

# carga de propiedades sensibles (correo)
spring.config.import=optional:classpath:application-correo.properties

# logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true

#---