spring.datasource.url=jdbc:h2:file:./mydatabase
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:classpath:application-correo.properties
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG