spring.application.name=biskit

server.port=${PORT:8080}
app.backend-url=https://biskitserver.onrender.com

# datasource
spring.jpa.database=h2
spring.datasource.driver-class-name=org.h2.Driver

# nombre base de datos
spring.datasource.url=jdbc:h2:file:./mydatabase
spring.datasource.username=sa
spring.datasource.password=

# consola de administracion de h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true

# datos de prueba
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

# logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true

# carga de propiedades sensibles (correo)
spring.config.import=optional:classpath:application-correo.properties

whatsapp.verify-token=mi_token_secreto_123
whatsapp.access-token=EAAaqqZCb1yzMBRoxyi9BZAlfeZCu9AP4KbmiccT958id6x9Se4i5SZCrZA550eCmvkJc6P7RhBc5KgjQY2QfBSzKHgQcU4UXN4jHlQumffrCiq8wMdqAyiN0DlZBSZBdCEH0KAvUC16qWi4Ynj2q7aAXDZAx6QRaw1zBKxk7MCsXgZBD1nCArQnpizpSjMhZCFsnJCqkS12wBruvpLQFsSAjlJc11sofEGR0TB40cL
whatsapp.phone-number-id=1151865241345341
whatsapp.api-url=https://graph.facebook.com/v25.0/1151865241345341/messages
