spring.datasource.url=jdbc:h2:file:./mydatabase
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.mail=TRACE
logging.level.org.springframework.boot.autoconfigure.mail=TRACE
logging.level.org.eclipse.angus.mail=TRACE
logging.level.org.eclipse.angus.mail.smtp=TRACE
logging.level.jakarta.mail=TRACE
logging.level.jakarta.activation=TRACE

spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000